services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: messaging-service-db
    environment:
      POSTGRES_DB: messaging_service
      POSTGRES_USER: messaging_user
      POSTGRES_PASSWORD: messaging_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U messaging_user -d messaging_service"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - messaging-network

  # Messaging Service Application
  messaging-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messaging-service-app
    environment:
      - PORT=8080
      - SERVER_READ_TIMEOUT=30s
      - SERVER_WRITE_TIMEOUT=30s
      - SERVER_IDLE_TIMEOUT=60s
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=messaging_service
      - DB_USER=messaging_user
      - DB_PASSWORD=messaging_password
      - DB_MAX_OPEN_CONNS=25
      - DB_MAX_IDLE_CONNS=5
      - DB_CONN_MAX_LIFETIME=5m
      - EMAIL_PROVIDER_TYPE=mock
      - SENDGRID_API_KEY=
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - messaging-network

volumes:
  postgres_data:
    driver: local

networks:
  messaging-network:
    driver: bridge 